# POD documentation - main docs before the code

=head1 NAME

GenOOx::Data::File::SAMbwa - Read SAM format files generated by BWA

=head1 SYNOPSIS

    # Object that manages a sam file. 

    # To initialize 
    my $sam_file = GenOOx::Data::File::SAMbwa->new(
        file            => undef,
    );


=head1 DESCRIPTION

    This object implements methods to read a sam file line by line.

=head1 EXAMPLES

    # Create object
    my $sam_file = GenOOx::Data::File::SAMbwa->new(
          file => 't/sample_data/sample.sam.gz'
    );
    
    # Read one record at a time
    my $sam_record = $sam_file->next_record();

=cut

# Let the code begin...

package GenOOx::Data::File::SAMbwa;


#######################################################################
#######################   Load External modules   #####################
#######################################################################
use Modern::Perl;
use autodie;
use Moose;
use namespace::autoclean;


#######################################################################
#########################   Load GenOO modules   ######################
#######################################################################
use GenOO::Data::File::SAM::Record;


#######################################################################
############################   Inheritance   ##########################
#######################################################################
extends 'GenOO::Data::File::SAM';


#######################################################################
############################   Finalize   #############################
#######################################################################
__PACKAGE__->meta->make_immutable;

1;
